### ISSUE TITLE
Detach from default program

### ISSUE THREAD

**Issue by Kouhzx** [bho3538/OpenWindowsPhotoViewer#1]
I've stumbled on your very useful modification by chance,
https://stackoverflow.com/a/76817324
and it's really nice to know somehow someone got this very special case settled by this modification!

The problem for me at the moment is, that your .exe seems to be linked to the default windows program to open images - which in my case is Pictureflect Image Viewer (a similiar viewer as the default Windows Photo one). It even works there, but after a few images they fail to load and you need to reopen them to 'refresh', which is not very practical. Just surprising they share that behaviour in some way.

Is there a way it could be always linked to the default Windows Photo Viewer without affecting the 'set as default' chosen one? (Another way would be to optimize it to work for Pictureflect app, but that's not really your responsibility - except the bug of failing to reload is easily to fix but I can't judge.

**Comment by bho3538** [comment]
![image](https://github.com/bho3538/OpenWindowsPhotoViewer/assets/12496720/36255668-9e32-4095-8ce7-ea268e11ef89)


PictureflectPhotoViewer looks like UWP App and all UWP program require background RPC server to read other files.
If user double-click to open file in explorer, explorer run background RPC server to communicate opened UWP program.

To keep run RPC server in background (running from unknown UWP api) , OpenImaeViewer.exe run loop in background and find current app is still running (using process name). 

if app still running -> openimageviewer.exe does not terminate and keep RPC server running.

![image](https://github.com/bho3538/OpenWindowsPhotoViewer/assets/12496720/f8851164-9750-4202-bbe4-757a614b3bf3)

I added 'Pictureflect exe' file at code to watch app is running and it work fine. (please donwload 2.0 version)

'Is there a way it could be always linked to the default Windows Photo Viewer without affecting the 'set as default' chosen one?'
--> Currently there is no UWP api (or I can't find yet) to open file with specified app, so that can't fix it

**Comment by Kouhzx** [comment]
That's just...beautiful, it works so well!
I really didn't think it would be 'easily' to fix it for Pictureflect as well, you did magnificient work!
On the note, it seems strange that this isn't something which gets fixed in both softwares by the companies themselves, but stays as an annoyance for years without having a look at it.
But you did it so well, thank you so much for your effort!
